apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    project: test
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

